# Be sure to restart your server when you modify this file.
#
# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
    secret_key_base: a0ae9165bce2408476a14cb52480f19107bea2659e8c93ecc84a6da94343d601864f1bdbfd1881a4eb99fe7bf9a2b7d5247a57e45a11e306715adcb4d8aab858

test:
    secret_key_base: 82f2d285a7e1d7ef5838ca3fa0cba755a821e56671cf84bf9e16ab7b0c6941e811c05eb311c580e40e91dccc0c06c5c63e333d137bbadb0608731095a930ade7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
    secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
